title: Miasteam - Ecommerce Operation Agency
email: lyanthinh03@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Agency Tăng trưởng E-commerce & Performance Marketing.

url: "https://miasteam.click" 
baseurl: ""

permalink: /:title/

# Build settings
markdown: kradmdown
theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache  # Đảm bảo bạn đã thêm dòng này
  - jekyll-sitemap        # Đảm bảo bạn đã thêm dòng này
  - minimal-mistakes-jekyll # <-- THÊM DÒNG NÀY ĐỂ SỬA LỖI SASS/IMPORT

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - README.md
  - .github/
  - admin/
include:
  - admin
